spring:
  application:
    name: ws
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mycinema
    username: root
    password: liang19950110
    mybatis:
      mapper-locations: classpath:mapper/*.xml
      type-aliases-package: domain.entity.entity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8001
